[MainInfo]
CustomerName			= 
IpAddress 			= 192.168.0.1
IpAddressPort 			= 44405
ClientVersion 			= 1.04.05
ClientSerial 			= TbYehR2hFUPBKgZj
WindowName 			= Mu Online - Season 4
ScreenShotPath 			= ScreenShots\Screen(%02d_%02d-%02d-%02d)-%04d.jpg
penLauncher 			= 1
LauncherName 			= Launcher.exe
DebugConsole 			= 0
MaxInstance 			= 2
RequireAdmin 			= 1
RequireAdminMessage 		= 1
BlockVirtualMachine 		= 1

[PluginSystem]
AntiBypassDLL 			= 0
PluginName1 			=
PluginName2 			=
PluginName3 			=
PluginName4 			=
PluginName5 			=

[LuaSystemClient]
ReloadLua 			= 0
OnlyCryptedLua 			= 0
PrivateCode 			= X9kPqW2vT7rZ4cL8mB5jYfN3sH6tA1u

[SystemRequirements]
;==========================================================
; CheckRequeriments = Habilita a Verificação de sistema
; CheckWindowsVersion = Versão do Windows (7, 8, 10, 11)
; MinMemoryRAMCheck   = Minimo de memoria RAM
; MinCPUCoreCheck     = Minimo de Núcleos do Processador
; MinVideoMemory      = Minimo de VRAM da Placa de Vídeo
;==========================================================
CheckRequeriments 		= 1
CheckWindowsVersion 		= 10
MinMemoryRAMCheck 		= 3
MinCPUCoreCheck 		= 4
MinVideoMemory	 		= 0

[Interface]
; WidesCreenType
; 	0 = Mantem Interface travada no do 1366x768
; 	1 = Reduz Interface conforme Resolução Aumenta
WidesCreenType			= 0
DisableClassSUM		 	= 0
VideoLogin		 	= 1

[Custom]
;==========================================================
; 0 = Disable | 1 = Enable
;==========================================================
LoadingLegend 			= 1
LoadingImageCount 		= 15
GMGiftPlayerTrade 		= 1
TCAAllowTrade 			= 1
LuckyTalismanAllowTrade 	= 1
SkillDisableEffect 		= 0
ShowFPSWindow	 		= 1
BlockSellTemporayNPC 		= 1
MountMiniSafeZone		= 1
TooltipAnimation		= 1
NoDelayPotion			= 1

[HardwareID]
;=================================================================================
; GetHWID: 1 = Obter HardwareID do Player
; ShowHWID: 1 = Exibe o HWID na janela do Jogo
; BlockHWID: HWID Bloqueados separados por vírgulas
; Ex: 55D3B74A-92FFC6EA-F25CA223-8D28B7EF,55D3B74A-92FFC6EA-F25CA223-8D28B7EF...
;=================================================================================
GetHWID 			= 1
ShowHWID 			= 0
BlockHWID 			=
